/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef mmhyph_h
#define mmhyph_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdbool.h>
#include <stdint.h>

typedef struct HyphDic HyphDic;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

bool find_hyphen_values_file(const HyphDic *dic,
                             const char *word,
                             uint32_t word_len,
                             uint8_t *hyphens,
                             uint32_t hyphens_len);

bool find_hyphen_values_raw(const uint8_t *dic_buf,
                            uint32_t dic_len,
                            const char *word,
                            uint32_t word_len,
                            uint8_t *hyphens,
                            uint32_t hyphens_len);

void free_hyphenation_file(HyphDic *dic);

const HyphDic *load_hyphenation_file(const char *path);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* mmhyph_h */
